# Main config with general settings
[general]
import = [
    "/home/zilero/.config/alacritty/themes/kanagawa_wave.toml",
    "/home/zilero/.config/alacritty/keybindings.toml"
]

[env]
TERM = "alacritty"

# Window settings
[window]
dynamic_title = true
decorations = "none"

[window.class]
instance = "Alacritty"
general = "Alacritty"

# Font settings
[font]
builtin_box_drawing = true
size = 22.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.bold_italic]
style = "Bold Italic"

# Scroll settings
[scrolling]
history = 10000
multiplier = 6

# Selection settings
[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

# Shell settings
[terminal.shell]
program = "/usr/bin/fish"
