themes:
  - name: "Kanagawa"
    colors:
      - "#658594"
      - "#9CABCA"
      - "#FF5D62"
      - "#C0A36E"
      - "#E6C384"
      - "#6A9589"
      - "#FFA066"
      - "#98BB6C"
      - "#E46876"
      - "#7FB4CA"
      - "#957FB8"
      - "#7E9CD8"
      - "#7AA89F"
      - "#D27E99"
      - "#E82424"
      - "#938AA9"
      - "#2D4F67"
      - "#223249"
      - "#727169"
      - "#DCD7BA"
      - "#16161D"
      - "#1E1F28"
      - "#2A2A37"
      - "#363646"
      - "#54546D"