# Основные цвета
[colors.primary]
background = "#282a36"     # Цвет фона терминала
foreground = "#f8f8f2"     # Основной цвет текста
bright_foreground = "#ffffff"  # Цвет яркого текста
dim_foreground = "#c7c7c7"    # Цвет приглушенного текста

# Цвет курсора
[colors.cursor]
text = "#282a36"    # Цвет текста под курсором
cursor = "#f8f8f2"  # Цвет самого курсора

# Стандартные цвета (используются для обычного текста)
[colors.normal]
black = "#21222c"    # Черный (для текста и фона)
red = "#ff5555"      # Красный (ошибки, предупреждения)
green = "#50fa7b"    # Зеленый (успешные операции)
yellow = "#f1fa8c"   # Желтый (предупреждения, выделения)
blue = "#bd93f9"     # Синий (информация, ссылки)
magenta = "#ff79c6"  # Пурпурный (специальные элементы)
cyan = "#8be9fd"     # Голубой (комментарии, дополнительная информация)
white = "#f8f8f2"    # Белый (основной текст)

# Яркие цвета (используются для выделения и жирного текста)
[colors.bright]
black = "#6272a4"    # Яркий черный
red = "#ff6e6e"      # Яркий красный
green = "#69ff94"    # Яркий зеленый
yellow = "#ffffa5"   # Яркий желтый
blue = "#d6acff"     # Яркий синий
magenta = "#ff92df"  # Яркий пурпурный
cyan = "#a4ffff"     # Яркий голубой
white = "#ffffff"    # Яркий белый

# Приглушенные цвета (используются для неактивных элементов)
[colors.dim]
black = "#14151b"    # Тусклый черный
red = "#cc4444"      # Тусклый красный
green = "#40c962"    # Тусклый зеленый
yellow = "#c1c970"   # Тусклый желтый
blue = "#9776c7"     # Тусклый синий
magenta = "#cc619e"  # Тусклый пурпурный
cyan = "#70c7ca"     # Тусклый голубой
white = "#c7c7c7"    # Тусклый белый

# Цвета выделения
[colors.selection]
text = "CellForeground"  # Цвет текста при выделении
background = "#44475a"   # Цвет фона при выделении

# Цвета поиска
[colors.search]
matches = { foreground = "#44475a", background = "#50fa7b" }         # Цвета для найденных совпадений
focused_match = { foreground = "#44475a", background = "#ffb86c" }   # Цвета для активного совпадения